### ISSUE TITLE
Useful Features

### ISSUE THREAD

**Issue by Hxtch2** [PrisonTeam/Prison#83] opened 2018-04-13 06:22 UTC
I have to say the fix for the /ranks modules has helped us tremendously thank you for that.

It would be nice to be able to modify the rankup message or all the message associated with /ranks that players see to something that best fits our server so like when it says congratulations you have ranked up to {rank} it would be nice to modify that and also prestige, multipliers, autoblock, autosmelt, notify when inventory is filled, would be some good additions that would basically be optional ofc and yea this Prison 3 would be almost the complete plugin for prison if it had these features.

I hope these would be taken into consideration.

**EDIT**: @DylanFPS

**Comment by DylanFPS** [comment] 2018-04-13 13:17
> autoblock, autosmelt,

Prison Ranks works independently to Prison Mines. You'll have to use permissions to change this.

> It would be nice to be able to modify the rankup message or all the message associated with /ranks

Soon we're migrating Ranks over to the Prison 3 locale system, so it's just a matter of time!

> prestige

The modules issue was actually caused by us beginning to implement prestige, it's not ready yet though.

> multipliers

You'd have to do this through your economy plugin, as in Ranks there isn't really a way to 'multiply' the speed in which a user ranks up, the user buys a rank using money from the economy plugin.

> notify when inventory is filled

While you can do this with other plugins, I'm sure there'll be no harm in adding this in Prison Mines as long as there is an option to disable it.

**Prestige**: Duplicate of #68 
**Notify when inventory is filled**: Feature Request, not done
**Ranks Localization**: Not done

**Comment by Crystalz-PrisonSupport** [comment] 2020-06-25 15:22
This ticket has been closed. If you have any other issues please open a new ticket.

**Closed by Crystalz-PrisonSupport** 2020-06-25 15:22 UTC
Labels: Feature, Module
