### ISSUE TITLE
Allow full editing of mines Ui discriptions

### ISSUE THREAD

**Issue by Josh-65** [PrisonTeam/Prison#243] opened 2022-12-20 22:38 UTC
### Which module are you submitting this issue for?
Core

### Describe the issue you are experiencing.
I haven't found a way to edit/remove these values in the mines section of the GUI config file
![image](https://user-images.githubusercontent.com/26977075/208780162-eb0e3115-f0c5-49e1-914a-39a274ab6de2.png)

**Comment by rbluer** [comment] 2022-12-20 23:46
Thanks for the suggestion Josh.  Thanks for taking the time to suggest it.

Duplicate of issue #242.

I'm closing this issue since it's really tied to your other issue that you've reported since it's also related to mine GUIs.

**Closed by rbluer** 2022-12-20 23:46 UTC
Labels: Duplicate
