### ISSUE TITLE
Couple Errors on 1.20.1

### ISSUE THREAD

**Issue by mercurialmusic** [PrisonTeam/Prison#251] opened 2023-06-19 06:19 UTC
### Which module are you submitting this issue for? 

Core (maybe?)

### Describe the issue you are experiencing.
Include details such as what you did, what happened, and what you think should have happened.

Getting a couple errors in Paper 1.20.1 -- I understand it may not be supported yet but creating this in case it's useful.
Most command use gives the following: 
https://gist.github.com/mercurialmusic/b37b49de6070bb031a0752ef237f8a44
And often also comes with:
https://gist.github.com/mercurialmusic/bc4d80a8a242eb08e5fe2767ff48204e

Players are not able to use anything that has a GUI. The /mines command by itself gives both of the above errors at once. Players are able to use /mines tp A, though (for example).

### Describe the steps to reproduce the problem.
Here, you should tell us what we need to know in order to cause the same problem on our machines, so that we may debug it. Please include your Spigot, Prison, and dependency versions. This section is only needed if you are making a bug report.

Running Prison-3.3.0-alpha.14b on Paper 1.20.1 (git-Paper-35)

Thanks!

**Comment by RayneBlox** [comment] 2023-06-19 06:40
Hi, I'm not a developer of this plugin but I have been given a statment by the developers. This error is due to the plugin you have is not updated to the latest NBT Library to work with 1.20.

The developer has put in a file in the support channel in the discord (https://discord.gg/DCJ3j6r) with an early access of the newest version, if you don't see the file, ping me (R_ayne is my username). And I will reply to the file or send you the file.

I can confirm that this new file that the developer made works flawlessly as I have used it, but don't expect it to be perfect.

Hope this helps,
Rayne.

**Comment by mercurialmusic** [comment] 2023-06-19 19:17
> Hi, I'm not a developer of this plugin but I have been given a statement by the developers. This error is due to the plugin you have is not updated to the latest NBT Library to work with 1.20.
> 
> The developer has put in a file in the support channel in the discord (https://discord.gg/DCJ3j6r) with an early access of the newest version, if you don't see the file, ping me (R_ayne is my username). And I will reply to the file or send you the file.
> 
> I can confirm that this new file that the developer made works flawlessly as I have used it, but don't expect it to be perfect.
> 
> Hope this helps, Rayne.

Lovely, thank you so much @RayneBlox ! Found the file without issue.



> [mercurialmusic](https://github.com/mercurialmusic): If you have any issues with the referenced file that RayneBlox mentioned, please ping me within discord.

Thank you! Will try it and will let you know if anything pops up.

**Comment by rbluer** [comment] 2023-06-24 15:55
I'm sorry everyone... I released an update on the discord server and forgot to mention it here.

https://discord.com/channels/332602419483770890/716731533851099187/1120826161426071653

I'm trying to fix a few minor outstanding issues while I'm letting the smaller community test these updates.  Once I am comfortable that no one is finding any other issues with v1.20.1 then I will post the latest updates to spigotmc and polymart.

I'm closing this ticket since there is a fix.  Thanks for the report! :)
  Blue

**Closed by rbluer** 2023-06-24 15:55 UTC
