### ISSUE TITLE
Mines Teleport safety not working after while

### ISSUE THREAD

**Issue by GodschildGaming** [PrisonTeam/Prison#103] opened 2018-06-20 14:30 UTC
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

Mines

### Describe the issue you are experiencing.
So when the mines reset they are suppose to teleport the player to safety but for some reason this will not work. it works when I do /reload then the teleport works again but if I re log then they don't work again

### Anything else we need to know?
using pex for permission handling and vault to load permissions. also have world edit, multiverse, punishmental, and PlotMe installed

**Comment by SevenSlayy** [comment] 2018-06-20 19:13
Duplicate of #82

**Comment by GodschildGaming** [comment] 2018-06-20 21:23
@SevenSlayy not duplication of #82 for his problem happened after a couple of resets my problem only happens when a person disconnects and then reconnects to the server

**Comment by DylanFPS** [comment] 2018-06-20 21:44
With the claim that this is a different cause in mind, we don't have enough information to believe that this issue is not a dupliate of #82. The relog thing is probably a coincidence as I imagine both issues go back to the same bug.

**Closed by DylanFPS** 2018-06-20 21:44 UTC
